### ISSUE TITLE
GIS Data Question

### ISSUE THREAD

**Issue by justinelliotmeyers** [capiscuas/osm-playground#2]
Hello,
Is the data for Indonesia available for review?

https://wiki.openstreetmap.org/wiki/Import/Catalogue/Indonesia/VillageBoundaries

Thanks,
Justin

**Comment by capiscuas** [comment]
Unfortunatelly not. It still has copyright issues. Indonesians NGO and organizations has brought the ministry to court because it is a case of public information being restrict.

**Comment by justinelliotmeyers** [comment]
Thanks @capiscuas
